### ISSUE TITLE
tumgreyspf-install error when smtpd_recipient_restrictions is the last variable

### ISSUE THREAD

**Issue by wforums** [linsomniac/tumgreyspf#6]
The tumgreyspf-install script is throwing the next error when the smtpd_recipient_restrictions is the last variable in the main.cf file:

```
Traceback (most recent call last):
File "./tumgreyspf-install", line 142, in <module>
for line in smtpd_recipient_restrictions:
TypeError: 'NoneType' object is not iterable
```

This happens with configuration files that look like this:

```
# See /usr/share/postfix/main.cf.dist for a commented, more complete version

# Left some lines out for brevity
inet_interfaces = all

smtpd_recipient_restrictions =
                permit_sasl_authenticated,
                permit_mynetworks,
                reject_unauth_destination
```

I'll make a pull request to fix this (easy fix) in a little while; it just needs an additional check if besides startLinenum, endLinenum is also not None, and if it is, assume the thing is at the end (or runs to the end)

**Comment by linsomniac** [comment]
Thanks for the patch, accepted.
